server:
  port: 8082

spring:
  application:
    name: servb
  datasource:
    url: jdbc:mysql://localhost:3306/servb
    username: root
    password: 3375

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
