spring:
  shardingsphere:
    datasource:
      names: datasource0,datasource1
      datasource0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/datasource0
        username: root
        password: 123456
      datasource1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/datasource1
        username: root
        password: 123456
    sharding:
      tables:
        t_order:
          actual-data-nodes: datasource$->{0..1}.order
          key-generator:
            column: id
            type: SNOWFLAKE
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: datasource_$->{id % 2}
#          table-strategy:
#            inline:
#              sharding-column:
#              algorithm-expression:
